### ISSUE TITLE
Java download URL on attribute default['java']['jdk']['8']['x86_64']['url'] is broken

### ISSUE THREAD

**Issue by JumpSplat96** [sous-chefs/java#517]
### Cookbook version
3.1.2

### Chef-client version
12.1

### Platform Details
RHEL-7.3

### Scenario:
Trying to install Java 8 with cookbook.

### Steps to Reproduce:
Converge with attribute on RedHat 7:
```
        "java": {
          "jdk_version": "8",
          "install_flavor": "oracle",
          "oracle": {
            "accept_oracle_download_terms": true
          }
        }
```

### Expected Result:
Install Java 8 JDK

### Actual Result:
```
---- Begin output of curl --fail --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz -o /tmp/packer-chef-solo/local-mode-cache/cache/jdk-8u191-linux-x64.tar.gz --connect-timeout 600   ----
Expected process to exit with [0], but received '22'
```

**Comment by JohnRoesler** [comment]
Looks like that version got moved to `http://download.oracle.com/otn/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz` per https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

I wonder if all the java 8 urls should get updated to the latest `8u201` 🤔

**Comment by colinbankier** [comment]
FYI, I'm seeing the same issue with java 11.

**Comment by JumpSplat96** [comment]
@JohnRoesler Seems like that link should do the trick! We'd also need the following checksum attribute to get it to work:
`default['java']['jdk']['8']['x86_64']['checksum']`
Any idea how to get that?

**Comment by JohnRoesler** [comment]
@colinbankier which Java 11 url?

**Comment by JumpSplat96** [comment]
So there are 2 problems:

1. The URLs have been changed, so the cookbook can't find the files to download
2. There has been an update to JDK 8.

When downloading JDK, anything less than the latest version requires authentication with an oracle account, which this cookbook does not supply and so it won't work. The following URL and checksum are for the latest version of JDK 8 (8u201). I am going to make a pull request for these changes.

```
default['java']['jdk']['8']['x86_64']['url'] = 'https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz'
default['java']['jdk']['8']['x86_64']['checksum'] = 'cb700cc0ac3ddc728a567c350881ce7e25118eaf7ca97ca9705d4580c506e370'
```

@colinbankier I have looked at the JDK 11 URL as well. I think these are the following attributes you need to fix it, but I'm unsure as I don't have a way to test it properly. Can you see if the following attributes will work for you?

```
default['java']['jdk']['11']['x86_64']['url'] = 'https://download.oracle.com/otn-pub/java/jdk/11.0.2+7/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_linux-x64_bin.tar.gz'
default['java']['jdk']['11']['x86_64']['checksum'] = '1f14572cae12adec64d28fdbf38935df7ced20b3efb54c33934b8bbecafdcd79'
```

**Comment by colinbankier** [comment]
Thanks @JumpSplat96  - yep, I had also found that URL and checksum, and those are working fine for me.
@JohnRoesler I don't have the log of the version it was failing on previously handy - but I guess that is not particularly useful now anyway.

**Comment by JohnRoesler** [comment]
Agreed. I'll look out for your pr @JumpSplat96

**Comment by y-batsianouski** [comment]
Hello, guys!

I Prepared PR: https://github.com/sous-chefs/java/pull/518
It's only for oracle jdk 8 x86_64. It's really affected us for now.

I hope someone will update other versions!

**Comment by nkadel-placester** [comment]
This is a frequent problem. Oracle has retained Sun's habit of discarding the hash-obfuscated old URL's, migrating them with little or no announcement to a new hash-obfuscated URL, and breaking automated deployment tools. Why they do this seems to be to force people through the web pages where they agree to the old Sun or new Oracle licensing terms. For reliable deployment, the *only* fix is to stage the tarballs or RPMs internally and point to that URL. This is why the README.md describes an artifactory URL.

Also, for RPM, it gives the opportunity to rename the file to *actually match the RPM*. The old Sun naming scheme for these RPMs has very little to do with the actual name of the installed RPM. I've reported it to Sun, and later Oracle, and never gotten an answer back, but the name that shows up in "yum" is not the name that shows up in RPM due to this. Rename the file in your yum repository to be based on `rpm -qp jdk[whaterver].rpm --qf '%{name}-%{version}-%{release}.%{arch}.rpm\n'`, and your yum package names match the RPM names. It's a chance to fix that confusion as well.

**Comment by JumpSplat96** [comment]
@y-batsianouski Thanks for making the PR! I was having some problems with getting the tests to run

**Comment by y-batsianouski** [comment]
> This is a frequent problem. Oracle has retained Sun's habit of discarding the hash-obfuscated old URL's, migrating them with little or no announcement to a new hash-obfuscated URL, and breaking automated deployment tools. Why they do this seems to be to force people through the web pages where they agree to the old Sun or new Oracle licensing terms. For reliable deployment, the _only_ fix is to stage the tarballs or RPMs internally and point to that URL. This is why the README.md describes an artifactory URL.
> 
> Also, for RPM, it gives the opportunity to rename the file to _actually match the RPM_. The old Sun naming scheme for these RPMs has very little to do with the actual name of the installed RPM. I've reported it to Sun, and later Oracle, and never gotten an answer back, but the name that shows up in "yum" is not the name that shows up in RPM due to this. Rename the file in your yum repository to be based on `rpm -qp jdk[whaterver].rpm --qf '%{name}-%{version}-%{release}.%{arch}.rpm\n'`, and your yum package names match the RPM names. It's a chance to fix that confusion as well.

Yes. But not everybody can host artifactory just for java binaries. So that is why time to time such PR will appear

**Comment by nkadel** [comment]
Artifactory? Why would you want that for a simple RPM repository, ideally a yum repository? Any lightweight web server capable of handling static content could provide that, such as nginx in its default configuration. In jact, for RHEL type hosts, simply creating a local yum mirror and using a "package" command, rather than the complex java cookbook, could work well. The java cookbook does have some features, such as activating an /etc/profile.d/jdk.sh to help keep java versions straight and consistently handling /etc/alternatives.

Artifactory just to handle a yum repository is.... overkill.

**Comment by Idun0** [comment]
Tried: 
default['java']['jdk']['8']['x86_64']['url'] = 'https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz'
default['java']['jdk']['8']['x86_64']['checksum'] = 'cb700cc0ac3ddc728a567c350881ce7e25118eaf7ca97ca9705d4580c506e370'
but now im getting a checksum error??? but when i check with 
shasum -a 256 jdk-8u201-linux-x64.tar.gz everything is correct???? not sure what im doing wrong? is anyone else having this same issue?

**Comment by damacus** [comment]
As we continually have Oracle URL problems like this we are shortly deprecating support for the Oracle falvour of the JDK. 

I would suggest moving to something like Corretto or AdoptOpenJDK for a better time.
