### ISSUE TITLE
Is Oracle JDK download still possible?

### ISSUE THREAD

**Issue by torbensky** [sous-chefs/java#542]
It seems that Oracle has once again broken download URL's (as of April 16) but this time I'm not sure if there is a way around it. When I tried to manually download the JDK I get redirected to an Oracle account sign in page. This is despite clicking the ToS accept radio button.

**Comment by sgrossberndt** [comment]
Same issue here. Maybe its time to dump oracle. Currently investigating whether gerrit runs with AdoptOpenJDK.

**Comment by salsa-dev** [comment]
This is probably related to the issue https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by kivagant-ba** [comment]
Only as a _temp_ workaround, the mirror can be used:
https://github.com/frekele/oracle-java/releases

```
default['java']['jdk']['8']['x86_64']['url'] = 'https://github.com/frekele/oracle-java/releases/download/8u212-b10/jdk-8u212-linux-x64.tar.gz'
# default['java']['jdk']['8']['x86_64']['url'] = 'https://download.oracle.com/otn/java/jdk/8u212-b10/59066701cf1a433da9770636fbc4c9aa/jdk-8u212-linux-x64.tar.gz' // doesn't work
default['java']['jdk']['8']['x86_64']['checksum'] = '3160c50aa8d8e081c8c7fe0f859ea452922eca5d2ae8f8ef22011ae87e6fedfb'

```

**Comment by damacus** [comment]
We're shortly going to be removing support for Oracle java from this cookbook, as it isn't possible to test due to licencing concerns. That said, all the other JDKs are getting some some love, and put into a maintained state. So if possible I'd recommend moving to one of the other JDKs. 

Let us know if this isn't suitable, and hopefully someone from Oracle can help us out testing.
